### ISSUE TITLE
Fail in running client_demo_simple.py on linux platform

### ISSUE THREAD

**Issue by siquinyao** [baidubce/pie#105]
问题描述：
采用百度流式识别开发，

    采用https://github.com/baidubce/pie中client_demo_simple.py

    修改增加username和password

    执行后在获取识别结果时返回错误

2020-04-02 14:49:38,231 - client_demo_simple.py[line:39] - ERROR: encounter an error: <_MultiThreadedRendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Socket closed"
    debug_error_string = "{"created":"@1585810168.220296937","description":"Error received from peer ipv4:182.61.0.38:8051","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Socket closed","grpc_status":14}"
>, will create a new channel and retry audio! times : 1、

重现步骤：
1. 已在CentOS 6.8 和 python2.7.13 重现
2. 已在CentOS 8.0 和 python 3.6.8 重现
3. Windows 7 和python3.8上都测试成功，未出现问题

**Comment by conanlcc** [comment]
同问，这里的username和password指的是哪里的用户名和密码？

**Comment by xiashuai-mr** [comment]
这里的username和password仅针对私有化用户公网功能测试开放，个人用户可移步百度公有云 https://cloud.baidu.com/ 测试~
