### ISSUE TITLE
怎样联系百度同学获取相关的信息？

### ISSUE THREAD

**Issue by hsxsix** [baidubce/pie#70]
![Screenshot_2019-05-23_11-53-10](https://user-images.githubusercontent.com/18223109/58224712-5ac20b00-7d51-11e9-8232-11da410a9191.png)

**Comment by cynricshu** [comment]
您好。我们这个是面向企业级用户的。
如果您是个人用户，请直接到 [http://ai.baidu.com/tech/speech](http://ai.baidu.com/tech/speech) 申请试用语音识别 SaaS 产品。
如果您是企业用户，想采购百度语音产品，可以留个联系方式，我们的商务人员会和您进一步沟通。
